name: Upload Package

on:
  push:
    branches: [main]
    paths: ['**.toml']

permissions:
  contents: read

jobs:
  deploy-private:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v5.5.0
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

#    - name: Build package
#      run: python -m build
#
#    - name: Publish package
#      uses: pypa/gh-action-pypi-publish@v1.12.4
#      with:
#        repository-url: https://pypi.stefanello.cc/
#        user: dudustefanello
#        password: ${{ secrets.PYPI_PASS }}
#        skip-existing: true