name: Django Test

on:
  push:
    branches: [main]
    paths: ['**.py']

permissions:
  contents: read

jobs:
  test-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install --extra-index-url https://dudustefanello:${{ secrets.PYPI_PASS }}@pypi.stefanello.cc/simple/ .

#    - name: Run testes
#      run: |
#        python manage.py test